### PR TITLE
Add JSON-Schema and Meteor SimpleSchema Adapters

### PR DESCRIPTION
**Pull request by dalcib**

### CODE REVIEW

**Comment by martinmcwhorter** [comment]
Looks good. FYI: I hope to have this published to NPM this week. 

Thanks for that.

**Comment by martinmcwhorter** [comment]
Dalci -- I updated the API slightly for the JSONSchema and SImpleSchema classes. 
- Instead of passing the class in, now you pass an instance: `jsonSchema.getSchema(new Person())`. This just makes the API consistent across adapters.
- I updated the adapters to get the property/field names from reflect-metadata. This just means that any property you want to use in your schema needs to have a decorator on it. As well, it means classes do not need to have default values, ie: `name: string = null;` becomes `name: string`.

**Comment by dalcib** [comment]
Nice Martin. Very good be able to throw away the nulls.
The Simple Schema is almost finished, but the JSONSchema is in early stage. It is very complex and powerful. This is only the basic implementation. I will be working on it to improve.

**Comment by martinmcwhorter** [comment]
:+1: Great! In the future it might be nice to populate model metadata from JSONSchema as well.

**Pull request merged**
